apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: edv5ltg9n-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:83ea7616cf8fd0b7030f7e945d79ac96c43a2a8a@sha256:abf04c7bc033bd91297223951042bf329b18f80c50a7ab3f8e0fd372941737a5
          name: container-image
