apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: edv5ltg9n-go
  janus-idp.io/tekton: edv5ltg9n-go
  backstage.io/kubernetes-id: edv5ltg9n-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: edv5ltg9n-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
